
# Find the Condor classad library

FIND_PATH(PYTHON_CLASSAD_INCLUDES classad_wrapper.h
  HINTS
  ${PYTHON_CLASSAD_DIR}
  $ENV{PYTHON_CLASSAD_DIR}
  /usr
  PATH_SUFFIXES include/pyclassad src/
)

FIND_LIBRARY(PYTHON_CLASSAD_LIB pyclassad
  HINTS
  ${PYTHON_CLASSAD_DIR}
  $ENV{PYTHON_CLASSAD_DIR}
  /usr
  PATH_SUFFIXES lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PythonClassAd DEFAULT_MSG PYTHON_CLASSAD_LIB PYTHON_CLASSAD_INCLUDES)

